version: '2'
services:
  frontend:
    image: shadiakiki1986/the-allocator
    volumes:
    # this doesnt work since docker cannot mount a single file
    # - ./the-allocator-config.json:/usr/share/the-allocator-config.json:ro
    # this works
    - ./config/:/usr/share/the-allocator-config:ro
    - ../the-allocator/:/usr/share/the-allocator/:ro # for development testing
    ports:
    - "6543:80"
    depends_on:
    - backend
  backend:
    image: nginx:alpine
    volumes:
    - ./www:/usr/share/nginx/html
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
    - "6544:80"
